### ISSUE TITLE
2018 n2c2 data availability 

### ISSUE THREAD

**Issue by esther1262** [uf-hobi-informatics-lab/ClinicalTransformerClassification#3]
Hi is 2018 n2c2 data publicly available, as I would like to replicate your codes:

https://github.com/uf-hobi-informatics-lab/ClinicalTransformerClassification/blob/580670f02baf9dc2a2112f5776935ec8a89a28f1/src/data_processing/preprocessing.ipynb#L535

Thanks

**Comment by bugface** [comment]
please contact the n2c2 team to get the data.  You have to sign DUA with them. We cannot share the dataset.

https://n2c2.dbmi.hms.harvard.edu/data-sets
